### ISSUE TITLE
Could Node.js be updated to a supported version?

### ISSUE THREAD

**Issue by FJCF76** [husisusi/officeonlin-install.sh#214] opened 2021-05-23 03:31 UTC
Hello,

Using Node.js 6.x LTS Boron is a requirement for the build process to work or could it be updated in the script?

Thanks!

**Comment by quenenni** [comment] 2021-05-24 14:23
Hello,

I don't know what Os you're using, but with Debian Buster, I'm using a more recent version of nodejs (v10.24.0).
Check #190

**Comment by FJCF76** [comment] 2021-05-25 23:05
I'm using Ubuntu 18.04 but the script is not working... still checking why...

**Comment by quenenni** [comment] 2021-05-26 12:23
If the problem is around NodeJs & Npm, try by installing manually the version you can and modify the script to remove the installation of these packages.

If still not working, can you put here the error you have.

**Comment by FJCF76** [comment] 2021-05-28 17:53
I have entered another issue about the problem I have building. Once I get the build process working, I'll modify to script to use a most recent version of NodeJS and provide to you the changes.

**Comment by joergmschulz** [comment] 2021-06-01 18:53
instead of opening multiple issues for the same problem (I'm referring to #215 ) , you should try and read the docs ... mentioned there. Would you mind closing this one?

**Comment by FJCF76** [comment] 2021-06-01 22:40
Hello, 

I thought they were different. One (#125) is not being able to build, and this one is about the NodeJs version (I intend to collaborate with an update to include a newer version once I can successfully compile (for error in #215 I didn't try a newer NodeJs version).

Is this ok? Or you still would like that I close this issue?

**Closed as completed** 2023-09-19 18:29 UTC
