### ISSUE TITLE
Unable to edit files

### ISSUE THREAD

**Issue by edmonaft** [husisusi/officeonlin-install.sh#162] opened 2018-07-04 12:41 UTC
Hi,

I have able to install using this script. I would like to express huge thanks for this.
I was able to view the contents of the documents I've uploaded.

One thing I am concerned though. I cannot edit a file whether it is existing or a new file.
What happens is that a brief "Connecting" phrase is displayed at the lower part of the screen and nothing happens. I cannot paste characters.

However, I can only do the following:

- Press enter and results correctly
- Insert and type comment

**Comment by Ark74** [comment] 2018-07-04 16:41
Could this be a duplicate of https://github.com/husisusi/officeonlin-install.sh/issues/160 ??

**Comment by edmonaft** [comment] 2018-07-05 11:19
This [fix ](https://github.com/husisusi/officeonlin-install.sh/issues/155#issuecomment-367507393)worked for me!

**Comment by ntinti** [comment] 2018-09-24 22:43
Same here. Document is opened, but can't be edited. In the status line there is a message "userxyz has leaved" (in german userxyz "hat verlassen") after less than a second the user is connected again. But every time the keyboard is used to type text the user is disconnected again. 
It seems the session isn't stored ore something else.
If it's really a problem of incompatible components/version - what is the latest working combination ?
```
About
LOOLWSD
3.2.0 (git hash: 99274582)
LOKit
Collabora OfficeDev 6.0-11 (git hash: 10f7cf9)
```
Error log:
```
wsd-03655-03734 2018-09-24 22:36:52.103364 [ docbroker_005 ] ERR  Invalid or unknown session [004e] to remove.| wsd/DocumentBroker.cpp:1069
wsd-03655-03734 2018-09-24 22:36:52.103373 [ docbroker_005 ] ERR  No socket associated with WebSocketHandler 0x0x7f1bb8013360| ./net/WebSocketHandler.hpp:100
wsd-03655-03744 2018-09-24 22:36:55.720072 [ docbroker_006 ] ERR  Invalid or unknown session [007b] to remove.| wsd/DocumentBroker.cpp:1069
wsd-03655-03744 2018-09-24 22:36:55.720081 [ docbroker_006 ] ERR  No socket associated with WebSocketHandler 0x0x7f1bb8012df0| ./net/WebSocketHandler.hpp:100
```

**Comment by Ark74** [comment] 2018-09-24 22:50
> what is the lates working combination ?

It would be a good idea to set a wiki documenting it.
So far, the closest to that would be: https://github.com/husisusi/officeonlin-install.sh/issues/155

I have running 
```
LOOLWSD
3.3.1 (git hash: 0adc773)
LOKit
Collabora OfficeDev 5.3-57
```
Cheers!

**Comment by ntinti** [comment] 2018-09-24 23:08
Thanks! If I downgrade - should I remove some directories manually - or does the script do all the things?

**Comment by Ark74** [comment] 2018-09-24 23:36
Please see here
https://github.com/husisusi/officeonlin-install.sh#command-line-usage

**Comment by ntinti** [comment] 2018-09-25 08:32
Thanks - got it working now:
```
About
LOOLWSD
3.2.0 (git hash: 99274582)
LOKit
Collabora OfficeDev 5.3-57 (git hash: 62b7f51)
```

**Comment by ntinti** [comment] 2018-09-26 15:16
Hey Luis
Which is your entry in the cfg to get version 3.3.1?

Thanks

**Comment by Ark74** [comment] 2018-09-26 15:54
If you are running a loolws server it would come handy to take a closer look at regex, I would say.
This value will be changing according to the evolution and changes of the branches of libreoffice online from upstream.

Anyhow, in case of TLDR, try,

`set_online_regex='collabora/collabora-online-3$'`

Cheers!

**Comment by ntinti** [comment] 2018-09-26 18:08
Thanks - there is a branche "private/kendy/monitoring-collabora-online-3" that matches my regex "collabora-online-3$" without the "collabora/" on beginning

**Comment by ntinti** [comment] 2018-12-16 23:04
Is there a working config with collbora 3.4?
My last compile was 3.3 

>#####################
>set_core_regex='cp-5.3$'
>set_online_regex='collabora/collabora-online-3$'
>lo_src_branch='distro/collabora/cp-5.3'
>lo_src_tag='cp-5.3-57'
>ool_src_tag='3.3.1-final'
>######################

Someone tried "cp-5.3-57" with collabora "3.4.0-5" and fails:
https://help.nextcloud.com/t/collabora-cp-5-3-59-cd-3-4-0-5/40770

**Comment by Ark74** [comment] 2018-12-17 16:20
I'm using online 3.4.x along with core 6.0.x
IDK if online 3.4 breaks due to core 5.3.

You might wanna test.

**Comment by husisusi** [comment] 2020-03-14 14:26
old

**Closed as completed by husisusi** 2020-03-14 14:26 UTC
